# Generated by Django 3.2.3 on 2021-06-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=255)),
                ('periodo_de_facturacion', models.CharField(max_length=255)),
                ('fecha_de_emision', models.CharField(max_length=255)),
                ('contrato', models.CharField(max_length=255)),
                ('inicio_contrato', models.CharField(max_length=255)),
                ('fin_contrato', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file_name', models.CharField(max_length=250)),
                ('n_pages', models.PositiveSmallIntegerField()),
                ('company', models.CharField(max_length=3)),
                ('power_contracted', models.FloatField(null=True)),
                ('duration', models.PositiveSmallIntegerField(null=True)),
                ('power_price', models.FloatField(null=True)),
                ('total_energy_consumed', models.FloatField(null=True)),
                ('total_energy_consumed_p1', models.FloatField(null=True)),
                ('total_energy_consumed_p2', models.FloatField(null=True)),
                ('energy_price', models.FloatField(null=True)),
                ('energy_price_p1', models.FloatField(null=True)),
                ('energy_price_p2', models.FloatField(null=True)),
                ('equipment_rental', models.FloatField(null=True)),
                ('electricity_tax_percentage', models.FloatField(null=True)),
                ('electricity_tax', models.FloatField(null=True)),
                ('energy_cost', models.FloatField(null=True)),
                ('energy_cost_p1', models.FloatField(null=True)),
                ('energy_cost_p2', models.FloatField(null=True)),
                ('power_cost', models.FloatField(null=True)),
                ('iva_percentage', models.PositiveSmallIntegerField(null=True)),
                ('iva_tax', models.FloatField(null=True)),
                ('tax_base', models.FloatField(null=True)),
                ('total_invoice', models.FloatField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
