# Generated by Django 3.2.3 on 2021-06-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=250)),
                ('total_amount', models.FloatField(default=60.72)),
                ('total_energy', models.FloatField(default=34.55)),
                ('total_power', models.FloatField(default=12.48)),
                ('total_services', models.FloatField(default=0.75)),
                ('total_taxes', models.FloatField(default=12.94)),
                ('total_energy_consumed', models.FloatField(default=193.0)),
                ('energy_price', models.FloatField(default=0.179017)),
                ('energy_cost', models.FloatField(default=34.55)),
                ('power_contracted', models.FloatField(default=3.3)),
                ('duration', models.PositiveSmallIntegerField(default=28)),
                ('power_price', models.FloatField(default=0.135031)),
                ('power_cost', models.FloatField(default=12.48)),
                ('equipment_rental', models.FloatField(default=0.75)),
                ('electricity_tax', models.FloatField(default=2.4)),
                ('iva_tax', models.FloatField(default=10.54)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
